const makeModules = (topicId, items) =>
  items.map(([number, title, summary, difficulty = "Core", minutes = 45]) => ({
    id: `${topicId}-${number}`,
    number,
    title,
    summary,
    difficulty,
    minutes,
  }));

export const topics = [
  {
    id: "asset-allocation",
    name: "Asset Allocation",
    shortName: "Asset Alloc.",
    weight: "15–20%",
    color: "#2f7d6d",
    soft: "#dcefe9",
    description: "Form capital market expectations and translate objectives into a strategic asset mix.",
    modules: makeModules("asset-allocation", [
      [1, "Capital Market Expectations, Part 1: Framework and Macro Considerations", "Build a CME framework, evaluate forecasting approaches, and connect the business cycle to asset returns.", "Advanced", 65],
      [2, "Capital Market Expectations, Part 2: Forecasting Asset Class Returns", "Forecast fixed-income, equity, real estate, and alternative returns using building-block and other methods.", "Advanced", 65],
      [3, "Overview of Asset Allocation", "Compare strategic and tactical allocation, asset-only versus liability-relative approaches, and key implementation choices.", "Core", 55],
      [4, "Principles of Asset Allocation", "Apply mean-variance optimization, risk budgeting, Black-Litterman, Monte Carlo simulation, and factor-based approaches.", "Advanced", 75],
      [5, "Asset Allocation with Real-World Constraints", "Adjust allocations for taxes, liquidity, ESG mandates, rebalancing costs, and behavioral factors.", "Advanced", 60],
    ]),
  },
  {
    id: "portfolio-construction",
    name: "Portfolio Construction",
    shortName: "Construction",
    weight: "15–20%",
    color: "#4e6fab",
    soft: "#e3eafa",
    description: "Build equity, fixed-income, and multi-asset portfolios that implement the strategic allocation efficiently.",
    modules: makeModules("portfolio-construction", [
      [6, "Overview of Equity Portfolio Management", "Compare passive, active, and factor-based approaches and the role of equities within a total portfolio.", "Core", 55],
      [7, "Overview of Fixed-Income Portfolio Management", "Compare liability-driven and total-return approaches and the major fixed-income mandate types.", "Core", 55],
      [8, "Asset Allocation to Alternative Investments", "Evaluate the role, sizing, liquidity budgeting, and due-diligence considerations for alternatives in a portfolio.", "Core", 55],
      [9, "Portfolio Management for Institutional Investors", "Compare objectives, constraints, and governance across pensions, endowments, insurers, and sovereign funds.", "Core", 60],
      [10, "Trading Costs and Electronic Markets", "Decompose implementation shortfall, compare order types and algorithms, and evaluate trading-venue choices.", "Core", 50],
      [11, "Case Study in Portfolio Management: Institutional", "Integrate objectives, constraints, allocation, and implementation in an institutional portfolio scenario.", "Advanced", 70],
    ]),
  },
  {
    id: "performance-measurement",
    name: "Performance Measurement",
    shortName: "Performance",
    weight: "5–10%",
    color: "#7b5a9c",
    soft: "#ece4f5",
    description: "Attribute and evaluate portfolio performance and select managers on a risk-adjusted, standardized basis.",
    modules: makeModules("performance-measurement", [
      [12, "Portfolio Performance Evaluation", "Decompose return using attribution analysis and evaluate performance appraisal ratios and benchmarks.", "Advanced", 65],
      [13, "Investment Manager Selection", "Apply a due-diligence framework covering manager universe, screening, and qualitative and quantitative selection factors.", "Core", 50],
      [14, "Overview of the Global Investment Performance Standards", "Understand GIPS purpose, composite construction, verification, and compliant presentation requirements.", "Core", 50],
    ]),
  },
  {
    id: "derivatives-risk",
    name: "Derivatives and Risk Management",
    shortName: "Derivatives",
    weight: "10–15%",
    color: "#b44f64",
    soft: "#f7e0e5",
    description: "Use options, swaps, forwards, and currency overlays to manage and reshape portfolio risk.",
    modules: makeModules("derivatives-risk", [
      [15, "Option Strategies", "Construct and evaluate covered calls, protective puts, spreads, collars, and straddles for defined objectives.", "Advanced", 70],
      [16, "Swaps, Forwards, and Futures Strategies", "Use interest rate, equity, and currency derivatives to adjust portfolio exposures efficiently.", "Advanced", 65],
      [17, "Currency Management: An Introduction", "Manage currency exposure using forwards, options, and hedge ratios and evaluate active currency strategies.", "Core", 55],
    ]),
  },
  {
    id: "ethics",
    name: "Ethical and Professional Standards",
    shortName: "Ethics",
    weight: "10–15%",
    color: "#b55d30",
    soft: "#f6e3d8",
    description: "Apply the Code and Standards to portfolio-management and asset-manager conduct at an advanced, case-based level.",
    modules: makeModules("ethics", [
      [18, "Code of Ethics and Standards of Professional Conduct", "Revisit the Code and the seven Standards with an emphasis on portfolio-management practice.", "Core", 45],
      [19, "Guidance for Standards I–VII", "Apply detailed guidance for each Standard to nuanced, exam-style professional-conduct situations.", "Advanced", 90],
      [20, "Application of the Code and Standards: Level III", "Work extended case studies that integrate multiple Standards within realistic advisory and management contexts.", "Advanced", 100],
      [21, "Asset Manager Code of Professional Conduct", "Understand the AMC's principles and compliance recommendations for asset-management firms.", "Core", 40],
    ]),
  },
  {
    id: "pathway-pm",
    name: "Pathway · Portfolio Management",
    shortName: "PM Pathway",
    weight: "30–35%*",
    color: "#2c7890",
    soft: "#dceef2",
    pathway: true,
    description: "Elective pathway for public-markets investing — one of three exam-day pathway choices (*shared 30–35% weight).",
    modules: makeModules("pathway-pm", [
      [22, "Passive Equity Investing", "Compare index-replication approaches, tracking error drivers, and implementation trade-offs.", "Core", 50],
      [23, "Active Equity Investing: Strategies", "Compare fundamental, quantitative, and activist approaches to generating equity alpha.", "Core", 55],
      [24, "Active Equity Investing: Portfolio Construction", "Build and evaluate active equity portfolios using risk models, constraints, and the fundamental law of active management.", "Advanced", 65],
      [25, "Liability-Driven and Index-Based Strategies", "Immunize, cash-flow match, and contingently immunize liabilities using fixed-income structures.", "Advanced", 65],
      [26, "Yield Curve Strategies", "Position duration and curve exposure to express rate-level, slope, and curvature views.", "Advanced", 60],
      [27, "Fixed-Income Active Management: Credit Strategies", "Implement credit-based strategies including spread positioning, structured credit, and cross-sector rotation.", "Advanced", 60],
      [28, "Trade Strategy and Execution", "Design pre-trade analysis, select execution tactics, and evaluate post-trade transaction-cost outcomes.", "Core", 45],
    ]),
  },
  {
    id: "pathway-pw",
    name: "Pathway · Private Wealth",
    shortName: "PW Pathway",
    weight: "30–35%*",
    color: "#a05d48",
    soft: "#f5e5df",
    pathway: true,
    description: "Elective pathway for high-net-worth clients — one of three exam-day pathway choices (*shared 30–35% weight).",
    modules: makeModules("pathway-pw", [
      [29, "The Private Wealth Management Industry", "Map the industry's participants, business models, and the services offered across the wealth lifecycle.", "Foundation", 40],
      [30, "Working with High-Net-Worth Clients", "Assess family dynamics, behavioral biases, and psychology that shape private-client decisions.", "Core", 50],
      [31, "Wealth Planning and Tax Considerations", "Evaluate tax regimes, tax-aware investing, and their effect on after-tax wealth accumulation.", "Advanced", 65],
      [32, "Investment Planning for the Private Client", "Build IPS-driven portfolios that reflect goals, constraints, concentrated positions, and liquidity needs.", "Advanced", 60],
      [33, "Preserving Wealth Through Risk Management", "Use insurance, hedging, and asset-protection structures to manage private-client risk exposures.", "Core", 50],
      [34, "Advising the Wealthy on Complex Situations", "Navigate concentrated stock, cross-border, and multi-generational complexities in private advisory work.", "Advanced", 55],
      [35, "Transferring Wealth: Gifts, Bequests, and Philanthropy", "Compare lifetime gifting, bequests, trusts, and charitable structures for efficient wealth transfer.", "Core", 55],
    ]),
  },
  {
    id: "pathway-pmk",
    name: "Pathway · Private Markets",
    shortName: "Priv. Markets",
    weight: "30–35%*",
    color: "#5f7741",
    soft: "#e6eddc",
    pathway: true,
    description: "Elective pathway for the general-partner perspective on alternatives — one of three exam-day pathway choices (*shared 30–35% weight).",
    modules: makeModules("pathway-pmk", [
      [36, "Private Investments and Structures", "Compare fund structures, terms, capital calls, and the roles of GPs and LPs across private markets.", "Foundation", 45],
      [37, "GP and LP Perspectives in the Investment Process", "Contrast sourcing, due diligence, and value-creation roles between general and limited partners.", "Core", 50],
      [38, "Private Equity: Company Lifecycle", "Analyze venture, growth, and buyout strategies as a company matures from founding to exit.", "Core", 55],
      [39, "Private Debt Financing Strategies", "Compare direct lending, mezzanine, and distressed-debt strategies and their risk-return profiles.", "Core", 50],
      [40, "Private Special Situations and Distressed Investing", "Evaluate turnaround, distressed, and special-situation strategies across the capital structure.", "Advanced", 55],
      [41, "Private Real Estate: Investment and Value-Add Strategies", "Assess core, value-add, and opportunistic real-estate strategies and their return drivers.", "Core", 50],
      [42, "Infrastructure Investment and Project Lifecycle", "Analyze infrastructure asset types, financing structures, and risks across the project lifecycle.", "Core", 45],
    ]),
  },
];

export const allModules = topics.flatMap((topic) =>
  topic.modules.map((module) => ({ ...module, topicId: topic.id, topicName: topic.name, topicColor: topic.color, topicSoft: topic.soft }))
);

export const formulas = [
  { group: "Asset allocation", name: "Two-asset portfolio variance", formula: "σₚ² = w₁²σ₁² + w₂²σ₂² + 2w₁w₂σ₁σ₂ρ₁₂", note: "The building block for mean-variance optimization and corner portfolios." },
  { group: "Asset allocation", name: "Roy's safety-first ratio", formula: "SF ratio = (E(Rₚ) − Rᴸ) / σₚ", note: "Maximize the ratio to minimize the probability of falling below a threshold return." },
  { group: "Asset allocation", name: "Risk budget contribution", formula: "CTRᵢ = wᵢ × (Covᵢ,ₚ / σₚ)", note: "Each asset's share of total portfolio risk, used in risk-parity and risk-budgeting approaches." },
  { group: "Portfolio construction", name: "Fundamental law of active management", formula: "IR ≈ IC × √BR", note: "Information ratio scales with skill (IC) and breadth of independent bets (BR)." },
  { group: "Portfolio construction", name: "Implementation shortfall", formula: "IS = (Paper return − Actual portfolio return)", note: "Captures execution, delay, and opportunity costs versus a paper portfolio." },
  { group: "Portfolio construction", name: "Macaulay to modified duration", formula: "ModDur = MacDur / (1 + y/k)", note: "Converts time-weighted duration into a price-sensitivity measure." },
  { group: "Performance", name: "Sharpe ratio", formula: "Sharpe = (Rₚ − Rꜰ) / σₚ", note: "Excess return per unit of total risk; not valid for portfolios with negative excess return." },
  { group: "Performance", name: "Treynor ratio", formula: "Treynor = (Rₚ − Rꜰ) / βₚ", note: "Uses systematic risk only; appropriate for a well-diversified sub-portfolio." },
  { group: "Performance", name: "Jensen's alpha", formula: "α = Rₚ − [Rꜰ + βₚ(Rₘ − Rꜰ)]", note: "Risk-adjusted excess return over the CAPM-predicted return." },
  { group: "Performance", name: "Information ratio", formula: "IR = (Rₚ − Rᵦ) / σ(Rₚ − Rᵦ)", note: "Active return per unit of active (tracking) risk versus the benchmark." },
  { group: "Derivatives", name: "Covered call maximum gain", formula: "Max gain = (X − S₀) + c₀", note: "Capped upside once the stock is called away at the strike." },
  { group: "Derivatives", name: "Protective put maximum loss", formula: "Max loss = S₀ − X + p₀", note: "The put floors downside risk at the strike, net of premium paid." },
  { group: "Derivatives", name: "Covered interest rate parity", formula: "F = S × (1 + rᴅᶜ) / (1 + rꜰᶜ)", note: "Links forward points to the interest-rate differential between two currencies." },
  { group: "Derivatives", name: "Minimum-variance hedge ratio", formula: "h* = ρ × (σₛ / σꜰ)", note: "The futures/forward position size that minimizes hedged portfolio variance." },
  { group: "Private markets", name: "Distributed to paid-in capital", formula: "DPI = Cumulative distributions / Paid-in capital", note: "Realized return multiple for a private-fund investor." },
  { group: "Private markets", name: "Total value to paid-in capital", formula: "TVPI = (Distributions + Residual value) / Paid-in capital", note: "Combines realized and unrealized value into one multiple." },
];

export const questions = [
  {
    id: 1, topic: "asset-allocation", module: 4,
    prompt: "In mean-variance optimization, the set of portfolios offering the highest expected return for each level of risk is called the:",
    options: ["Capital allocation line", "Efficient frontier", "Security market line"], answer: 1,
    explanation: "First principle: for every risk level, the efficient frontier plots the maximum achievable expected return across feasible asset combinations. The CAL blends a risk-free asset with a risky portfolio; the SML is a CAPM pricing relationship, not a frontier of portfolios. Answer: Efficient frontier.",
  },
  {
    id: 2, topic: "asset-allocation", module: 4,
    prompt: "Relative to mean-variance optimization, resampled (Monte Carlo) optimization is most likely used to address:",
    options: ["Estimation error and corner solutions", "Currency translation risk", "GIPS compliance"], answer: 0,
    explanation: "First principle: MVO is highly sensitive to small input errors, often producing extreme, concentrated ('corner') allocations. Resampling averages many simulated optimizations drawn from the input uncertainty, producing more diversified, stable weights. Answer: Estimation error and corner solutions.",
  },
  {
    id: 3, topic: "portfolio-construction", module: 10,
    prompt: "A large buy order that moves the market price up before the full order is filled illustrates which trading cost?",
    options: ["Market impact", "Explicit commission", "Delay cost"], answer: 0,
    explanation: "First principle: implementation shortfall decomposes cost into delay, market impact, and commissions/fees. Price moving against the trader as size is worked into the market is market impact, distinct from the cost of delaying the trade or paying explicit fees. Answer: Market impact.",
  },
  {
    id: 4, topic: "portfolio-construction", module: 6,
    prompt: "An index fund experiencing high tracking error relative to its benchmark most likely used which replication approach?",
    options: ["Full replication", "Stratified sampling with a small basket", "Physical replication of every constituent"], answer: 1,
    explanation: "First principle: full replication holds every constituent at benchmark weight, minimizing tracking error. Sampling-based (optimized) replication holds a representative subset, trading off lower cost/complexity for higher tracking error, especially in broad or illiquid indexes. Answer: Stratified sampling with a small basket.",
  },
  {
    id: 5, topic: "performance-measurement", module: 12,
    prompt: "A manager outperforms its benchmark, but the outperformance is fully explained by the manager's tilt toward the value factor. This is best described as:",
    options: ["Pure selection effect", "Style/factor exposure, not manager skill", "Currency effect"], answer: 1,
    explanation: "First principle: performance attribution separates return into allocation, selection, and interaction (or factor) effects. Return explained entirely by a known factor tilt reflects style exposure the client could obtain passively, not idiosyncratic security-selection skill. Answer: Style/factor exposure, not manager skill.",
  },
  {
    id: 6, topic: "performance-measurement", module: 12,
    prompt: "A portfolio with Rₚ = 12%, Rꜰ = 3%, σₚ = 15%, and β = 1.2 has a Treynor ratio closest to:",
    options: ["0.60", "7.50", "9.00"], answer: 1,
    explanation: "First principle: Treynor = (Rₚ − Rꜰ) / β. Substitute: (12 − 3) / 1.2 = 9 / 1.2 = 7.5. Sharpe would instead divide by σₚ (giving 0.60), which is a different risk denominator. Answer: 7.50.",
  },
  {
    id: 7, topic: "performance-measurement", module: 14,
    prompt: "Under GIPS, a firm constructs composites primarily to:",
    options: ["Report only its best-performing accounts", "Group discretionary portfolios with similar strategies for fair comparison", "Avoid disclosing fee schedules"], answer: 1,
    explanation: "First principle: GIPS requires all fee-paying, discretionary portfolios to be included in at least one composite defined by strategy, preventing cherry-picking of favorable results and enabling apples-to-apples prospective client comparisons. Answer: Group discretionary portfolios with similar strategies for fair comparison.",
  },
  {
    id: 8, topic: "derivatives-risk", module: 15,
    prompt: "An investor who owns a stock and sells an out-of-the-money call against it has constructed a:",
    options: ["Protective put", "Covered call", "Bull spread"], answer: 1,
    explanation: "First principle: a covered call combines a long stock position with a short call, capping upside in exchange for premium income while leaving downside largely exposed below the premium cushion. A protective put instead buys a put for downside insurance. Answer: Covered call.",
  },
  {
    id: 9, topic: "derivatives-risk", module: 17,
    prompt: "If domestic interest rates rise relative to a foreign currency, covered interest rate parity implies the domestic currency should trade at a forward:",
    options: ["Premium", "Discount", "No change"], answer: 1,
    explanation: "First principle: F = S × (1 + r_domestic)/(1 + r_foreign). A higher domestic rate raises the numerator, but no-arbitrage forces the higher-yielding currency to trade at a forward discount so covered returns equalize across currencies. Answer: Discount.",
  },
  {
    id: 10, topic: "ethics", module: 19,
    prompt: "A portfolio manager allocates a favorable, oversubscribed IPO allocation across client accounts strictly pro rata by order size submitted in advance. This most likely complies with:",
    options: ["Standard III(B): Fair Dealing", "Standard IV(A): Loyalty to Employer", "Standard V(A): Diligence and Reasonable Basis"], answer: 0,
    explanation: "First principle: Standard III(B) requires fair, not necessarily equal, treatment of clients, achieved through pre-disclosed, systematic allocation procedures. A pro rata, pre-established methodology satisfies this fairness requirement for oversubscribed offerings. Answer: Standard III(B): Fair Dealing.",
  },
  {
    id: 11, topic: "ethics", module: 21,
    prompt: "The Asset Manager Code of Professional Conduct is best described as:",
    options: ["A mandatory law enforced by regulators", "A voluntary code firms can adopt to demonstrate ethical commitment", "A replacement for the CFA Institute Code and Standards"], answer: 1,
    explanation: "First principle: the AMC is a voluntary framework asset-management firms may claim compliance with to signal ethical and professional practice to clients; it supplements, and does not replace, the individual-level Code and Standards. Answer: A voluntary code firms can adopt to demonstrate ethical commitment.",
  },
  {
    id: 12, topic: "pathway-pw", module: 31,
    prompt: "For a private client, tax-loss harvesting is most likely used to:",
    options: ["Increase current-year taxable income", "Offset realized gains and reduce current tax liability", "Eliminate estate tax exposure"], answer: 1,
    explanation: "First principle: realizing losses on depreciated positions creates a tax loss that can offset realized capital gains (and, within limits, ordinary income), lowering the client's current-year tax bill while preserving overall portfolio exposure via replacement securities. Answer: Offset realized gains and reduce current tax liability.",
  },
  {
    id: 13, topic: "pathway-pmk", module: 39,
    prompt: "A private fund with cumulative distributions of 60 and paid-in capital of 100 has a DPI closest to:",
    options: ["0.60", "1.60", "0.40"], answer: 0,
    explanation: "First principle: DPI = cumulative distributions / paid-in capital = 60 / 100 = 0.60. DPI captures only realized proceeds returned to the LP, excluding any remaining unrealized (residual) value, which TVPI would add back. Answer: 0.60.",
  },
  {
    id: 14, topic: "pathway-pm", module: 22,
    prompt: "Compared with a full-replication index fund, a sampling-based index fund on a broad, illiquid bond index most likely has:",
    options: ["Lower tracking error and lower cost", "Higher tracking error and lower cost", "Higher tracking error and higher cost"], answer: 1,
    explanation: "First principle: sampling holds a representative subset rather than every issue, cutting transaction and holding costs in an illiquid universe, but the smaller basket cannot track every constituent's return exactly, so tracking error rises versus full replication. Answer: Higher tracking error and lower cost.",
  },
];

export const topicLookup = Object.fromEntries(topics.map((topic) => [topic.id, topic]));
