const makeModules = (topicId, items) =>
  items.map(([number, title, summary, difficulty = "Core", minutes = 45]) => ({
    id: `${topicId}-${number}`,
    number,
    title,
    summary,
    difficulty,
    minutes,
  }));

export const topics = [
  {
    id: "quant",
    name: "Quantitative Methods",
    shortName: "Quant",
    weight: "6–9%",
    color: "#2f7d6d",
    soft: "#dcefe9",
    description: "The numerical toolkit for valuing cash flows, measuring risk, and testing evidence.",
    modules: makeModules("quant", [
      [1, "Rates and Returns", "Interpret required returns and decompose performance using money-weighted, time-weighted, arithmetic, and geometric measures.", "Foundation", 45],
      [2, "Time Value of Money in Finance", "Move cash flows across time, value annuities and perpetuities, and solve common investment applications.", "Foundation", 55],
      [3, "Statistical Measures of Asset Returns", "Describe return distributions with central tendency, dispersion, skewness, kurtosis, covariance, and correlation.", "Core", 55],
      [4, "Probability Trees and Conditional Expectations", "Apply conditional probability, Bayes’ rule, expected value, and probability trees to investment decisions.", "Core", 50],
      [5, "Portfolio Mathematics", "Combine asset returns and risk using weights, variance, covariance, correlation, and downside measures.", "Advanced", 60],
      [6, "Simulation Methods", "Use historical and Monte Carlo simulation to model uncertain outcomes and evaluate scenarios.", "Core", 45],
      [7, "Estimation and Inference", "Understand sampling, point estimates, confidence intervals, and the trade-off between precision and confidence.", "Advanced", 60],
      [8, "Hypothesis Testing", "Form hypotheses, select significance levels, interpret p-values, and distinguish Type I from Type II errors.", "Advanced", 65],
      [9, "Parametric and Non-Parametric Tests of Independence", "Choose and interpret tests for means, variances, correlation, and categorical independence.", "Advanced", 60],
      [10, "Simple Linear Regression", "Estimate and interpret a two-variable regression, its goodness of fit, assumptions, and prediction intervals.", "Advanced", 70],
      [11, "Introduction to Big Data Techniques", "Recognize big-data characteristics, machine-learning methods, data-processing steps, and analytical risks.", "Core", 40],
    ]),
  },
  {
    id: "economics",
    name: "Economics",
    shortName: "Economics",
    weight: "6–9%",
    color: "#4e6fab",
    soft: "#e3eafa",
    description: "How firms, policy, trade, currencies, and cycles shape investment outcomes.",
    modules: makeModules("economics", [
      [12, "The Firm and Market Structures", "Compare competitive environments, cost behavior, pricing power, and profit-maximizing output across market structures.", "Core", 60],
      [13, "Understanding Business Cycles", "Identify phases of the cycle and connect economic indicators, credit conditions, and sector behavior.", "Core", 50],
      [14, "Fiscal Policy", "Evaluate government spending, taxation, multipliers, debt, and the limits of fiscal intervention.", "Core", 45],
      [15, "Monetary Policy", "Explain central-bank objectives, policy tools, transmission channels, and the interaction with inflation and growth.", "Core", 50],
      [16, "Introduction to Geopolitics", "Assess geopolitical actors, cooperation, conflict, and the channels through which geopolitical risk affects markets.", "Foundation", 35],
      [17, "International Trade", "Apply comparative advantage, analyze trade restrictions, and understand trade agreements and their welfare effects.", "Core", 45],
      [18, "Capital Flows and the FX Market", "Map the foreign-exchange market, exchange-rate regimes, balance-of-payments accounts, and international flows.", "Advanced", 55],
      [19, "Exchange Rate Calculations", "Calculate cross rates, forward rates, appreciation, depreciation, and currency-converted investment returns.", "Advanced", 60],
    ]),
  },
  {
    id: "corporate",
    name: "Corporate Issuers",
    shortName: "Corporate",
    weight: "6–9%",
    color: "#a05d48",
    soft: "#f5e5df",
    description: "How businesses organize, allocate capital, finance operations, and govern stakeholders.",
    modules: makeModules("corporate", [
      [20, "Organizational Forms, Corporate Issuer Features, and Ownership", "Compare business forms and the economic features of public and private corporate ownership.", "Foundation", 35],
      [21, "Investors and Other Stakeholders", "Compare stakeholder claims, motivations, time horizons, and the relevance of environmental and social factors.", "Foundation", 35],
      [22, "Corporate Governance: Conflicts, Mechanisms, Risks, and Benefits", "Analyze principal-agent conflicts, board structures, governance mechanisms, and related risks.", "Core", 50],
      [23, "Working Capital and Liquidity", "Measure operating and cash-conversion cycles and evaluate short-term liquidity and financing choices.", "Core", 50],
      [24, "Capital Investments and Capital Allocation", "Apply NPV and IRR, assess project cash flows, and evaluate capital-allocation discipline.", "Advanced", 65],
      [25, "Capital Structure", "Evaluate debt and equity choices, leverage, weighted-average cost of capital, and capital-structure theories.", "Advanced", 60],
      [26, "Business Models", "Deconstruct how a company creates, delivers, and captures value and how its model affects risk and performance.", "Core", 40],
    ]),
  },
  {
    id: "fsa",
    name: "Financial Statement Analysis",
    shortName: "FSA",
    weight: "11–14%",
    color: "#7b5a9c",
    soft: "#ece4f5",
    description: "Read financial reports critically and translate accounting into decision-useful analysis.",
    modules: makeModules("fsa", [
      [27, "Introduction to Financial Statement Analysis", "Understand primary statements, footnotes, audit opinions, reporting standards, and the analyst’s process.", "Foundation", 45],
      [28, "Analyzing Income Statements", "Analyze revenue, expenses, unusual items, earnings per share, and common-size income statements.", "Core", 65],
      [29, "Analyzing Balance Sheets", "Evaluate assets, liabilities, equity classifications, liquidity, solvency, and balance-sheet presentation.", "Core", 60],
      [30, "Analyzing Statements of Cash Flows I", "Classify operating, investing, and financing cash flows and compare direct and indirect presentation.", "Advanced", 65],
      [31, "Analyzing Statements of Cash Flows II", "Convert cash-flow presentations and derive free cash flow and performance insights from cash data.", "Advanced", 65],
      [32, "Analysis of Inventories", "Compare inventory methods and analyze their effects on profit, taxes, cash flow, and financial ratios.", "Advanced", 60],
      [33, "Analysis of Long-Term Assets", "Assess capitalization, depreciation, impairment, revaluation, and derecognition of long-lived assets.", "Advanced", 60],
      [34, "Topics in Long-Term Liabilities and Equity", "Analyze bonds, leases, pensions, share-based compensation, and changes in shareholders’ equity.", "Advanced", 70],
      [35, "Analysis of Income Taxes", "Reconcile accounting and taxable income and interpret deferred tax assets, liabilities, and valuation allowances.", "Advanced", 65],
      [36, "Financial Reporting Quality", "Distinguish reporting quality from earnings quality and detect biased estimates, classification, and manipulation.", "Core", 50],
      [37, "Financial Analysis Techniques", "Use activity, liquidity, solvency, profitability, and valuation ratios with decomposition and peer comparison.", "Core", 65],
      [38, "Introduction to Financial Statement Modeling", "Build coherent revenue, margin, working-capital, and balance-sheet forecasts using historical drivers.", "Advanced", 70],
    ]),
  },
  {
    id: "equity",
    name: "Equity Investments",
    shortName: "Equity",
    weight: "11–14%",
    color: "#b07b26",
    soft: "#f6ecd6",
    description: "Understand markets, assess businesses, and value ownership claims.",
    modules: makeModules("equity", [
      [39, "Market Organization and Structure", "Understand market participants, order types, trading venues, clearing, settlement, and market quality.", "Foundation", 50],
      [40, "Security Market Indexes", "Explain index construction, weighting, rebalancing, uses, and sources of index return differences.", "Core", 45],
      [41, "Market Efficiency", "Compare forms of efficiency, testable implications, anomalies, behavioral explanations, and active-management limits.", "Core", 50],
      [42, "Overview of Equity Securities", "Compare common and preferred shares, private and public equity, return sources, and investor rights.", "Foundation", 40],
      [43, "Company Analysis: Past and Present", "Evaluate a company’s business, financial history, disclosures, competitive position, and operating drivers.", "Core", 55],
      [44, "Industry and Competitive Analysis", "Define an industry, assess its structure and life cycle, and apply competitive-forces analysis.", "Core", 55],
      [45, "Company Analysis: Forecasting", "Forecast revenue, margins, reinvestment, and earnings by connecting operational drivers to financial statements.", "Advanced", 65],
      [46, "Equity Valuation: Concepts and Basic Tools", "Apply dividend, multiplier, and asset-based valuation approaches and interpret required return.", "Advanced", 75],
    ]),
  },
  {
    id: "fixed-income",
    name: "Fixed Income",
    shortName: "Fixed Income",
    weight: "11–14%",
    color: "#2c7890",
    soft: "#dceef2",
    description: "Price contractual cash flows and measure interest-rate, curve, and credit risk.",
    modules: makeModules("fixed-income", [
      [47, "Fixed-Income Instrument Features", "Read bond terms, indentures, covenants, seniority, and embedded provisions that shape investor cash flows.", "Foundation", 40],
      [48, "Fixed-Income Cash Flows and Types", "Compare plain, floating, index-linked, amortizing, and contingent cash-flow structures.", "Foundation", 45],
      [49, "Fixed-Income Issuance and Trading", "Map issuers, investors, indexes, primary issuance, secondary trading, and market liquidity.", "Foundation", 40],
      [50, "Fixed-Income Markets for Corporate Issuers", "Compare short- and long-term corporate funding, commercial paper, repos, investment-grade, and high-yield markets.", "Core", 45],
      [51, "Fixed-Income Markets for Government Issuers", "Compare sovereign, non-sovereign, agency, and supranational funding and trading practices.", "Core", 40],
      [52, "Fixed-Income Bond Valuation: Prices and Yields", "Price bonds on and between coupon dates and connect coupon, maturity, yield, and price.", "Advanced", 70],
      [53, "Yield and Yield Spread Measures for Fixed-Rate Bonds", "Calculate and interpret current yield, YTM, option-adjusted measures, and benchmark spreads.", "Advanced", 65],
      [54, "Yield and Yield Spread Measures for Floating-Rate Instruments", "Calculate discount margins and money-market yields for floating-rate and short-term instruments.", "Advanced", 60],
      [55, "The Term Structure of Interest Rates: Spot, Par, and Forward Curves", "Derive and apply spot, par, and forward rates to price cash flows and interpret the curve.", "Advanced", 75],
      [56, "Interest Rate Risk and Return", "Decompose bond return and connect investment horizon, reinvestment risk, price risk, and Macaulay duration.", "Advanced", 65],
      [57, "Yield-Based Bond Duration Measures and Properties", "Calculate modified duration, money duration, and PVBP and explain their sensitivity drivers.", "Advanced", 70],
      [58, "Yield-Based Bond Convexity and Portfolio Properties", "Use duration plus convexity to estimate price changes and aggregate risk at portfolio level.", "Advanced", 65],
      [59, "Curve-Based and Empirical Fixed-Income Risk Measures", "Apply effective and key-rate durations and distinguish analytical from empirical sensitivity.", "Advanced", 60],
      [60, "Credit Risk", "Decompose expected credit loss and understand ratings, spread drivers, seniority, and recovery.", "Core", 55],
      [61, "Credit Analysis for Government Issuers", "Assess sovereign willingness and capacity to pay using institutions, growth, fiscal, and external factors.", "Core", 50],
      [62, "Credit Analysis for Corporate Issuers", "Evaluate business risk, financial risk, leverage, coverage, liquidity, and structural subordination.", "Core", 60],
      [63, "Fixed-Income Securitization", "Explain pooling, tranching, credit enhancement, parties, and risks in securitized structures.", "Core", 50],
      [64, "Asset-Backed Security Instrument and Market Features", "Analyze ABS collateral, cash-flow waterfalls, credit support, and prepayment or extension exposure.", "Core", 50],
      [65, "Mortgage-Backed Security Instrument and Market Features", "Compare mortgage products and agency structures and analyze prepayment and contraction risk.", "Advanced", 60],
    ]),
  },
  {
    id: "derivatives",
    name: "Derivatives",
    shortName: "Derivatives",
    weight: "5–8%",
    color: "#b44f64",
    soft: "#f7e0e5",
    description: "Understand contingent claims, forward commitments, replication, and no-arbitrage pricing.",
    modules: makeModules("derivatives", [
      [66, "Derivative Instrument and Derivative Market Features", "Define derivative markets and compare exchange-traded and OTC instruments, participants, and risks.", "Foundation", 40],
      [67, "Forward Commitment and Contingent Claim Features and Instruments", "Compare forwards, futures, swaps, options, and credit derivatives by payoff and obligation.", "Foundation", 45],
      [68, "Derivative Benefits, Risks, and Issuer and Investor Uses", "Evaluate hedging, speculation, arbitrage, transformation, leverage, liquidity, and counterparty risk.", "Core", 40],
      [69, "Arbitrage, Replication, and the Cost of Carry in Pricing Derivatives", "Use no-arbitrage, replication, and carrying costs to connect spot and forward prices.", "Advanced", 60],
      [70, "Pricing and Valuation of Forward Contracts", "Distinguish price from value and calculate forward values before and at expiration.", "Advanced", 65],
      [71, "Pricing and Valuation of Futures Contracts", "Understand daily settlement and compare futures pricing and value behavior with forwards.", "Advanced", 55],
      [72, "Pricing and Valuation of Interest Rate and Other Swaps", "View swaps as a series of forwards and value fixed-versus-floating cash-flow differences.", "Advanced", 65],
      [73, "Pricing and Valuation of Options", "Explain option moneyness, intrinsic and time value, arbitrage bounds, and sensitivity drivers.", "Advanced", 70],
      [74, "Option Replication Using Put–Call Parity", "Apply put–call parity to replicate positions, detect mispricing, and construct synthetic exposures.", "Advanced", 60],
      [75, "Valuing a Derivative Using a One-Period Binomial Model", "Build up/down payoffs, hedge ratios, and risk-neutral values in a one-period tree.", "Advanced", 70],
    ]),
  },
  {
    id: "alternatives",
    name: "Alternative Investments",
    shortName: "Alternatives",
    weight: "7–10%",
    color: "#5f7741",
    soft: "#e6eddc",
    description: "Private capital, real assets, hedge funds, and digital assets beyond public stocks and bonds.",
    modules: makeModules("alternatives", [
      [76, "Alternative Investment Features, Methods, and Structures", "Compare access routes, legal structures, liquidity, fees, valuation, and diversification features.", "Foundation", 45],
      [77, "Alternative Investment Performance and Returns", "Calculate fee-adjusted returns and understand appraisal smoothing, stale prices, and return-measurement bias.", "Advanced", 55],
      [78, "Investments in Private Capital: Equity and Debt", "Compare venture, growth, buyout, and private-credit strategies, deal stages, value creation, and risks.", "Core", 55],
      [79, "Real Estate and Infrastructure", "Compare property and infrastructure features, valuation approaches, income drivers, vehicles, and risks.", "Core", 55],
      [80, "Natural Resources", "Analyze commodities, farmland, and timberland through spot-return, carry, operational, and inflation exposures.", "Core", 45],
      [81, "Hedge Funds", "Compare strategy families, fee structures, liquidity terms, leverage, biases, and due-diligence concerns.", "Core", 55],
      [82, "Introduction to Digital Assets", "Understand distributed ledgers, tokens, custody, consensus, return drivers, and principal investment risks.", "Core", 45],
    ]),
  },
  {
    id: "portfolio",
    name: "Portfolio Management",
    shortName: "Portfolio",
    weight: "8–12%",
    color: "#6b68a9",
    soft: "#e8e7f6",
    description: "Combine assets around objectives, constraints, behavior, and a disciplined risk process.",
    modules: makeModules("portfolio", [
      [83, "Portfolio Risk and Return: Part I", "Build portfolio expected return and variance and interpret diversification and the efficient frontier.", "Advanced", 70],
      [84, "Portfolio Risk and Return: Part II", "Apply beta, CAPM, the security market line, and risk-adjusted performance measures.", "Advanced", 70],
      [85, "Portfolio Management: An Overview", "Understand the portfolio process, investor types, asset management, pensions, and pooled vehicles.", "Foundation", 45],
      [86, "Basics of Portfolio Planning and Construction", "Translate client objectives and constraints into an IPS, strategic allocation, and portfolio choices.", "Core", 60],
      [87, "The Behavioral Biases of Individuals", "Distinguish cognitive errors from emotional biases and connect each to investment behavior.", "Core", 50],
      [88, "Introduction to Risk Management", "Build a risk-governance framework and identify, measure, modify, and budget financial and non-financial risk.", "Core", 50],
    ]),
  },
  {
    id: "ethics",
    name: "Ethical and Professional Standards",
    shortName: "Ethics",
    weight: "15–20%",
    color: "#b55d30",
    soft: "#f6e3d8",
    description: "Practice professional judgment and protect the integrity of clients, markets, and the profession.",
    modules: makeModules("ethics", [
      [89, "Ethics and Trust in the Investment Profession", "Explain why trust matters, recognize ethical challenges, and apply a structured ethical decision framework.", "Foundation", 45],
      [90, "Code of Ethics and Standards of Professional Conduct", "Understand the Code, the seven Standards, professional responsibilities, and enforcement context.", "Core", 55],
      [91, "Guidance for Standards I–VII", "Apply the Standards to realistic facts involving conduct, markets, clients, employers, analysis, conflicts, and responsibilities.", "Advanced", 120],
      [92, "Introduction to the Global Investment Performance Standards", "Understand the purpose, scope, fundamentals, composites, and presentation principles of GIPS.", "Core", 50],
      [93, "Ethics Application", "Integrate the ethical decision framework and Standards in mixed, exam-style scenarios.", "Advanced", 75],
    ]),
  },
];

export const allModules = topics.flatMap((topic) =>
  topic.modules.map((module) => ({ ...module, topicId: topic.id, topicName: topic.name, topicColor: topic.color, topicSoft: topic.soft }))
);

export const formulas = [
  { group: "Returns", name: "Holding period return", formula: "HPR = (P₁ − P₀ + D₁) / P₀", note: "Price change plus income, divided by beginning value." },
  { group: "Returns", name: "Geometric mean", formula: "Rᴳ = [∏(1 + Rₜ)]^(1/n) − 1", note: "Use for compounded performance across periods." },
  { group: "Time value", name: "Present value", formula: "PV = FV / (1 + r)ⁿ", note: "Discount one future cash flow to today." },
  { group: "Time value", name: "Growing perpetuity", formula: "PV = CF₁ / (r − g)", note: "Requires r > g; cash flow starts one period ahead." },
  { group: "Statistics", name: "Sample variance", formula: "s² = Σ(xᵢ − x̄)² / (n − 1)", note: "The sample estimator uses n − 1 degrees of freedom." },
  { group: "Statistics", name: "Standard error of the mean", formula: "SE(x̄) = s / √n", note: "Falls as sample size rises." },
  { group: "Corporate", name: "Net present value", formula: "NPV = Σ CFₜ / (1 + r)ᵗ − Initial outlay", note: "Accept an independent project when NPV is positive." },
  { group: "Corporate", name: "Weighted average cost of capital", formula: "WACC = wᴅrᴅ(1 − T) + wₑrₑ", note: "Use target market-value weights." },
  { group: "FSA", name: "Basic earnings per share", formula: "EPS = (NI − Preferred dividends) / Weighted avg. common shares", note: "Adjust the denominator for stock splits." },
  { group: "FSA", name: "Free cash flow to firm", formula: "FCFF = CFO + Interest(1 − T) − Capex", note: "Cash flow available to debt and equity capital." },
  { group: "FSA", name: "DuPont return on equity", formula: "ROE = Net margin × Asset turnover × Financial leverage", note: "Decomposes profitability, efficiency, and leverage." },
  { group: "Equity", name: "Gordon growth model", formula: "V₀ = D₁ / (r − g)", note: "Best for stable dividend growth with r > g." },
  { group: "Equity", name: "Justified forward P/E", formula: "P₀ / E₁ = Payout ratio / (r − g)", note: "Connects valuation to fundamentals." },
  { group: "Fixed income", name: "Full bond price", formula: "PV = Σ CFₜ / (1 + y)ᵗ", note: "Discount each promised cash flow at the appropriate periodic yield." },
  { group: "Fixed income", name: "Approximate price change", formula: "ΔP/P ≈ −ModDur·Δy + ½·Convexity·(Δy)²", note: "Duration is first-order; convexity improves the estimate." },
  { group: "Fixed income", name: "Expected credit loss", formula: "ECL = PD × LGD × Exposure", note: "Probability of default times loss severity and exposure." },
  { group: "Derivatives", name: "Forward price, no income", formula: "F₀(T) = S₀(1 + r)ᵀ", note: "Carry the spot asset forward at the financing rate." },
  { group: "Derivatives", name: "Put–call parity", formula: "c₀ + PV(X) = p₀ + S₀", note: "For European options with the same strike and expiry." },
  { group: "Portfolio", name: "Two-asset portfolio variance", formula: "σₚ² = w₁²σ₁² + w₂²σ₂² + 2w₁w₂σ₁σ₂ρ₁₂", note: "Correlation drives the diversification effect." },
  { group: "Portfolio", name: "Capital asset pricing model", formula: "E(Rᵢ) = Rꜰ + βᵢ[E(Rₘ) − Rꜰ]", note: "Expected return compensates systematic risk." },
  { group: "Portfolio", name: "Sharpe ratio", formula: "Sharpe = [Rₚ − Rꜰ] / σₚ", note: "Excess return per unit of total risk." },
  { group: "Alternatives", name: "Post-fee hedge fund return", formula: "Net return = Gross profit − Management fee − Incentive fee", note: "Apply fee base, high-water mark, and hurdle terms carefully." },
];

export const questions = [
  {
    id: 1, topic: "quant", module: 1,
    prompt: "A portfolio gains 20% in year 1 and loses 20% in year 2. Its two-year geometric mean return is closest to:",
    options: ["0.00%", "−2.02%", "−4.00%"], answer: 1,
    explanation: "First principle: geometric mean compounds the wealth factors, then annualizes. Step 1 — Ending wealth = 1.20 × 0.80 = 0.96. Step 2 — Annualized geometric return = 0.96^(1/2) − 1 = √0.96 − 1 ≈ −0.0202. Answer: −2.02%. Sanity: arithmetic mean is 0%, but volatility drag makes geometric mean negative.",
  },
  {
    id: 2, topic: "quant", module: 8,
    prompt: "Rejecting a true null hypothesis is best described as:",
    options: ["A Type I error", "A Type II error", "Test power"], answer: 0,
    explanation: "First principle: error types are defined relative to the truth of H₀. Type I = reject a true H₀ (false positive; probability = α). Type II = fail to reject a false H₀ (false negative; probability = β). Power = 1 − β. Answer: Type I error.",
  },
  {
    id: 3, topic: "economics", module: 12,
    prompt: "In long-run perfect competition, economic profit most likely tends toward:",
    options: ["Monopoly profit", "Zero", "Accounting loss"], answer: 1,
    explanation: "First principle: free entry/exit drives price to minimum long-run ATC. At that point economic profit = 0 (normal return only). Accounting profit can still be positive. Answer: Zero economic profit.",
  },
  {
    id: 4, topic: "economics", module: 19,
    prompt: "If INR/USD moves from 83 to 85, the Indian rupee has most likely:",
    options: ["Appreciated against USD", "Depreciated against USD", "Remained unchanged"], answer: 1,
    explanation: "First principle: quote INR/USD = rupees per one dollar. More INR per USD means the rupee buys less USD → INR depreciated (USD appreciated). 83 → 85 is more INR per USD. Answer: Depreciated against USD.",
  },
  {
    id: 5, topic: "corporate", module: 24,
    prompt: "For two mutually exclusive projects, the preferred decision rule is generally to choose the project with the:",
    options: ["Highest positive NPV", "Shortest payback", "Highest accounting profit"], answer: 0,
    explanation: "First principle: NPV = PV(inflows) − PV(outflows) measures value added in today's money. For mutually exclusive projects, pick the highest NPV (if positive). Payback ignores TVM/cash after cutoff; accounting profit is not cash. Answer: Highest positive NPV.",
  },
  {
    id: 6, topic: "fsa", module: 31,
    prompt: "Under the indirect cash-flow method, an increase in accounts receivable is most likely:",
    options: ["Added to net income", "Deducted from net income", "A financing cash flow"], answer: 1,
    explanation: "First principle: CFO (indirect) starts at NI and adjusts to cash. ↑AR means revenue recognized without cash collected → cash < NI → deduct the increase. Classification: operating working capital, not financing. Answer: Deducted from net income.",
  },
  {
    id: 7, topic: "fsa", module: 37,
    prompt: "Holding all else constant, a faster collection of receivables will most likely:",
    options: ["Increase the cash conversion cycle", "Reduce the cash conversion cycle", "Reduce inventory turnover"], answer: 1,
    explanation: "First principle: CCC = DIO + DSO − DPO. Faster collections → lower DSO → lower CCC. Inventory turnover is unaffected if inventory policy is unchanged. Answer: Reduce the cash conversion cycle.",
  },
  {
    id: 8, topic: "equity", module: 40,
    prompt: "Compared with a price-weighted index, a market-cap-weighted index gives more influence to securities with:",
    options: ["Higher total market value", "Higher share price only", "Lower free float"], answer: 0,
    explanation: "First principle: weight = (security's market cap) / (index total market cap), often float-adjusted. Price-weighted indexes care about share price, not firm size. Lower free float typically reduces (not increases) weight. Answer: Higher total market value.",
  },
  {
    id: 9, topic: "equity", module: 46,
    prompt: "A stable-growth company is expected to pay a dividend of 4 next year. If r = 10% and g = 4%, value is closest to:",
    options: ["40.00", "66.67", "100.00"], answer: 1,
    explanation: "First principle (Gordon): V₀ = D₁ / (r − g), requiring r > g. Substitute: V₀ = 4 / (0.10 − 0.04) = 4 / 0.06 = 66.67. Trap: 4/0.10 = 40 is a zero-growth perpetuity; 4/0.04 = 100 ignores the required return correctly. Answer: 66.67.",
  },
  {
    id: 10, topic: "fixed-income", module: 52,
    prompt: "For an option-free bond, if the required yield rises, the bond's price will most likely:",
    options: ["Rise", "Fall", "Remain unchanged"], answer: 1,
    explanation: "First principle: Price = Σ CFₜ / (1 + y)^t. Higher y → larger discount factors in the denominator → lower PV. Inverse price–yield relationship for option-free bonds. Answer: Fall.",
  },
  {
    id: 11, topic: "fixed-income", module: 57,
    prompt: "A bond has modified duration of 5.2. For a 25 bp yield increase, its estimated percentage price change is closest to:",
    options: ["−0.13%", "−1.30%", "+1.30%"], answer: 1,
    explanation: "First principle: ΔP/P ≈ −ModDur × Δy (Δy in decimal). Step: −5.2 × 0.0025 = −0.013 = −1.30%. Sign is negative because yields rose. Answer: −1.30%.",
  },
  {
    id: 12, topic: "fixed-income", module: 60,
    prompt: "Loss given default is best described as one minus the:",
    options: ["Probability of default", "Recovery rate", "Credit spread"], answer: 1,
    explanation: "First principle: ECL = PD × LGD × Exposure, and LGD = 1 − recovery rate. PD is the chance of default; spread is market compensation. Answer: Recovery rate.",
  },
  {
    id: 13, topic: "derivatives", module: 74,
    prompt: "For European options on a non-dividend-paying stock, put–call parity is:",
    options: ["c + PV(X) = p + S", "c + p = S + X", "c − p = PV(X) + S"], answer: 0,
    explanation: "First principle: fiduciary call (c + PV(X)) and protective put (p + S) have identical terminal payoffs for European options on non-dividend stock → equal values today: c + PV(X) = p + S. Answer: c + PV(X) = p + S.",
  },
  {
    id: 14, topic: "alternatives", module: 81,
    prompt: "A hedge fund high-water mark most directly prevents an incentive fee from being charged on:",
    options: ["Recovered prior losses", "Gross positive returns", "Assets under management"], answer: 0,
    explanation: "First principle: incentive fees apply only above the highest prior NAV (high-water mark). After a loss, gains that merely recover prior losses are not incentive-fee-eligible until the HWM is cleared. Answer: Recovered prior losses.",
  },
  {
    id: 15, topic: "portfolio", module: 83,
    prompt: "Diversification benefit is greatest when the correlation between two assets is closest to:",
    options: ["+1.0", "0.0", "−1.0"], answer: 2,
    explanation: "First principle: σₚ² = w₁²σ₁² + w₂²σ₂² + 2w₁w₂σ₁σ₂ρ₁₂. Lower ρ shrinks the covariance term. Minimum risk (for some weights) occurs at ρ = −1. Answer: −1.0.",
  },
  {
    id: 16, topic: "portfolio", module: 84,
    prompt: "Under CAPM, investors are compensated for bearing:",
    options: ["Total risk", "Systematic risk", "Security-specific risk"], answer: 1,
    explanation: "First principle: E(Rᵢ) = Rf + βᵢ[E(Rm) − Rf]. Only non-diversifiable (systematic) risk, measured by beta, earns a risk premium. Idiosyncratic risk can be diversified away. Answer: Systematic risk.",
  },
  {
    id: 17, topic: "ethics", module: 91,
    prompt: "When local law is less strict than the Code and Standards, a member should follow:",
    options: ["Local law only", "The stricter Code and Standards", "Employer policy only"], answer: 1,
    explanation: "First principle: comply with the stricter of applicable law and the Code/Standards. If local law is looser, the Code still binds. Answer: The stricter Code and Standards.",
  },
  {
    id: 18, topic: "ethics", module: 91,
    prompt: "An analyst may accept a gift from a client for strong performance if the analyst most appropriately:",
    options: ["Keeps it confidential", "Obtains written consent from the employer", "Donates half to charity"], answer: 1,
    explanation: "First principle: gifts can create conflicts (Standard I(B)/IV(B) spirit). Written employer disclosure/consent lets the firm assess and monitor the conflict. Confidentiality or partial donation does not clear the conflict. Answer: Obtain written employer consent.",
  },
];

export const topicLookup = Object.fromEntries(topics.map((topic) => [topic.id, topic]));
